/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.PGM.SavePGMFile;
import view.PGM.OpenPGMFile;
import controller.Controlador;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import view.PPM.OpenPPMFile;
import view.PPM.SavePPMFile;

/**
 *
 * @author willm
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        groupMediaMediana = new javax.swing.ButtonGroup();
        groupLaplaciano = new javax.swing.ButtonGroup();
        groupExtracaoRGB = new javax.swing.ButtonGroup();
        groupJuncaoR = new javax.swing.ButtonGroup();
        groupJuncaoG = new javax.swing.ButtonGroup();
        griupJuncaoB = new javax.swing.ButtonGroup();
        groupExtracaoSalvarOuMemoria = new javax.swing.ButtonGroup();
        tabbedPane = new javax.swing.JTabbedPane();
        panelJuncaoExtracao = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        radioExtracaoRed = new javax.swing.JRadioButton();
        radioExtracaoGreen = new javax.swing.JRadioButton();
        radioExtracaoBlue = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        radioExtracaoTodos = new javax.swing.JRadioButton();
        radioExtracaoSalvarImagem = new javax.swing.JRadioButton();
        radioExtracaoUtilizarEmMemoria = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        RedRed = new javax.swing.JRadioButton();
        RedGreen = new javax.swing.JRadioButton();
        RedBlue = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        GreenRed = new javax.swing.JRadioButton();
        GreenGreen = new javax.swing.JRadioButton();
        GreenBlue = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        BlueRed = new javax.swing.JRadioButton();
        BlueGreen = new javax.swing.JRadioButton();
        BlueBlue = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        buttonJuntar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelEqualizacaoGeral = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panelFiltragemEspacial = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        buttonFiltro = new javax.swing.JButton();
        spinnerQuantidadeFiltro = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioMedia = new javax.swing.JRadioButton();
        radioMediana = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerHighBoostMedia = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        textHighBoostConstante = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioTipo1 = new javax.swing.JRadioButton();
        radioTipo2 = new javax.swing.JRadioButton();
        radioTipo3 = new javax.swing.JRadioButton();
        radioTipo4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        checkBoxAplicar = new javax.swing.JCheckBox();
        panelInformacoes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelRotacao = new javax.swing.JPanel();
        buttonRotacao90 = new javax.swing.JButton();
        buttonRotacao180 = new javax.swing.JButton();
        buttonRotacaoMenos90 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonEspelhamentoHorizontal = new javax.swing.JButton();
        buttonEspelhamentoVertical = new javax.swing.JButton();
        panelOperacacao = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonAdicao = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        spinnerConstante = new javax.swing.JSpinner();
        buttonSubtracao = new javax.swing.JButton();
        buttonMultiplicacao = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        textMultiplicacaoQuantidade = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        spinnerBinarizacao = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buttonBinarizacao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonNegativo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        spinnerResolucao = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panelTransformacaoPotencia = new javax.swing.JPanel();
        textConstanteTransformacao = new javax.swing.JTextField();
        textBetaTransformacao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        textOperacoes = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de processamento digital de imagens");

        groupExtracaoRGB.add(radioExtracaoRed);
        radioExtracaoRed.setSelected(true);
        radioExtracaoRed.setText("Red");

        groupExtracaoRGB.add(radioExtracaoGreen);
        radioExtracaoGreen.setText("Green");

        groupExtracaoRGB.add(radioExtracaoBlue);
        radioExtracaoBlue.setText("Blue");

        jLabel3.setText("Separação de cores");

        jButton2.setText("Extrair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        groupExtracaoRGB.add(radioExtracaoTodos);
        radioExtracaoTodos.setText("Todos");

        groupExtracaoSalvarOuMemoria.add(radioExtracaoSalvarImagem);
        radioExtracaoSalvarImagem.setSelected(true);
        radioExtracaoSalvarImagem.setText("Salvar imagem");
        radioExtracaoSalvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExtracaoSalvarImagemActionPerformed(evt);
            }
        });

        groupExtracaoSalvarOuMemoria.add(radioExtracaoUtilizarEmMemoria);
        radioExtracaoUtilizarEmMemoria.setText("Utilizar em memória (extrai o canal selecionado e é transformado em imagem PGM)");
        radioExtracaoUtilizarEmMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExtracaoUtilizarEmMemoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(radioExtracaoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioExtracaoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioExtracaoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioExtracaoTodos))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radioExtracaoSalvarImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioExtracaoUtilizarEmMemoria)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioExtracaoRed)
                    .addComponent(radioExtracaoGreen)
                    .addComponent(radioExtracaoBlue)
                    .addComponent(radioExtracaoTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioExtracaoSalvarImagem)
                    .addComponent(radioExtracaoUtilizarEmMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        groupJuncaoR.add(RedRed);
        RedRed.setSelected(true);
        RedRed.setText("Red");

        groupJuncaoR.add(RedGreen);
        RedGreen.setText("Green");

        groupJuncaoR.add(RedBlue);
        RedBlue.setText("Blue");

        jLabel9.setText("Red");

        groupJuncaoG.add(GreenRed);
        GreenRed.setText("Red");

        groupJuncaoG.add(GreenGreen);
        GreenGreen.setSelected(true);
        GreenGreen.setText("Green");

        groupJuncaoG.add(GreenBlue);
        GreenBlue.setText("Blue");

        jLabel10.setText("Green");

        griupJuncaoB.add(BlueRed);
        BlueRed.setText("Red");

        griupJuncaoB.add(BlueGreen);
        BlueGreen.setText("Green");

        griupJuncaoB.add(BlueBlue);
        BlueBlue.setSelected(true);
        BlueBlue.setText("Blue");

        jLabel11.setText("Blue");

        buttonJuntar.setText("Juntar");
        buttonJuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJuntarActionPerformed(evt);
            }
        });

        jLabel12.setText("Junção de RGB");

        jLabel13.setText("O canal possuirá a cor selecionado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(RedBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RedRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RedGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(GreenBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GreenRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GreenGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(BlueBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BlueRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BlueGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonJuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlueRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlueGreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlueBlue))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GreenRed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GreenGreen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GreenBlue))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RedRed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RedGreen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RedBlue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonJuntar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelJuncaoExtracaoLayout = new javax.swing.GroupLayout(panelJuncaoExtracao);
        panelJuncaoExtracao.setLayout(panelJuncaoExtracaoLayout);
        panelJuncaoExtracaoLayout.setHorizontalGroup(
            panelJuncaoExtracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelJuncaoExtracaoLayout.setVerticalGroup(
            panelJuncaoExtracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJuncaoExtracaoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Junção e extração do RGB", panelJuncaoExtracao);

        jButton3.setText("Equalizar o histograma global");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEqualizacaoGeralLayout = new javax.swing.GroupLayout(panelEqualizacaoGeral);
        panelEqualizacaoGeral.setLayout(panelEqualizacaoGeralLayout);
        panelEqualizacaoGeralLayout.setHorizontalGroup(
            panelEqualizacaoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEqualizacaoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        panelEqualizacaoGeralLayout.setVerticalGroup(
            panelEqualizacaoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEqualizacaoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Equalização de histograma geral", panelEqualizacaoGeral);

        buttonFiltro.setText("Aplicar filtro");
        buttonFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltroActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade (precisa ser impar)");

        jLabel4.setText("Tipo de filtro");

        groupMediaMediana.add(radioMedia);
        radioMedia.setSelected(true);
        radioMedia.setText("Média");

        groupMediaMediana.add(radioMediana);
        radioMediana.setText("Mediana");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spinnerQuantidadeFiltro)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioMediana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerQuantidadeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFiltro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("High boost");

        jLabel7.setText("Média");

        jLabel8.setText("Constante");

        jButton4.setText("Aplicar high boost");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        textHighBoostConstante.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 360, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(spinnerHighBoostMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(textHighBoostConstante))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerHighBoostMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHighBoostConstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Laplaciano");

        groupLaplaciano.add(radioTipo1);
        radioTipo1.setSelected(true);
        radioTipo1.setText("Tipo 1");

        groupLaplaciano.add(radioTipo2);
        radioTipo2.setText("Tipo 2");

        groupLaplaciano.add(radioTipo3);
        radioTipo3.setText("Tipo 3");

        groupLaplaciano.add(radioTipo4);
        radioTipo4.setText("Tipo 4");

        jButton5.setText("Aplicar laplaciano");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        checkBoxAplicar.setSelected(true);
        checkBoxAplicar.setText("Aplicar a máscara na imagem");
        checkBoxAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxAplicar))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFiltragemEspacialLayout = new javax.swing.GroupLayout(panelFiltragemEspacial);
        panelFiltragemEspacial.setLayout(panelFiltragemEspacialLayout);
        panelFiltragemEspacialLayout.setHorizontalGroup(
            panelFiltragemEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltragemEspacialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltragemEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFiltragemEspacialLayout.setVerticalGroup(
            panelFiltragemEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltragemEspacialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltragemEspacialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Filtragem espacial", panelFiltragemEspacial);

        jLabel2.setText("Informações sobre a imagem carregada");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelInformacoesLayout = new javax.swing.GroupLayout(panelInformacoes);
        panelInformacoes.setLayout(panelInformacoesLayout);
        panelInformacoesLayout.setHorizontalGroup(
            panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelInformacoesLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 603, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformacoesLayout.setVerticalGroup(
            panelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Informações da imagem", panelInformacoes);

        buttonRotacao90.setText("90º");
        buttonRotacao90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotacao90ActionPerformed(evt);
            }
        });

        buttonRotacao180.setText("180º");
        buttonRotacao180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotacao180ActionPerformed(evt);
            }
        });

        buttonRotacaoMenos90.setText("-90º");
        buttonRotacaoMenos90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRotacaoMenos90ActionPerformed(evt);
            }
        });

        jLabel14.setText("Rotacionar a imagem em:");

        jLabel15.setText("Espelhamento");

        buttonEspelhamentoHorizontal.setText("Horizontal");
        buttonEspelhamentoHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspelhamentoHorizontalActionPerformed(evt);
            }
        });

        buttonEspelhamentoVertical.setText("Vertical");
        buttonEspelhamentoVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspelhamentoVerticalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRotacaoLayout = new javax.swing.GroupLayout(panelRotacao);
        panelRotacao.setLayout(panelRotacaoLayout);
        panelRotacaoLayout.setHorizontalGroup(
            panelRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRotacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRotacaoLayout.createSequentialGroup()
                        .addComponent(buttonRotacao90)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRotacao180)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRotacaoMenos90))
                    .addComponent(jLabel14)
                    .addGroup(panelRotacaoLayout.createSequentialGroup()
                        .addComponent(buttonEspelhamentoHorizontal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEspelhamentoVertical))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(620, Short.MAX_VALUE))
        );
        panelRotacaoLayout.setVerticalGroup(
            panelRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRotacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRotacao90)
                    .addComponent(buttonRotacao180)
                    .addComponent(buttonRotacaoMenos90))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEspelhamentoHorizontal)
                    .addComponent(buttonEspelhamentoVertical))
                .addContainerGap(456, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Rotação e espelhamento", panelRotacao);

        buttonAdicao.setText("Adição");
        buttonAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicaoActionPerformed(evt);
            }
        });

        jLabel16.setText("Quantidade");

        buttonSubtracao.setText("Subtração");
        buttonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtracaoActionPerformed(evt);
            }
        });

        buttonMultiplicacao.setText("Multiplicação");
        buttonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplicacaoActionPerformed(evt);
            }
        });

        jLabel19.setText("Quantidade multiplicação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(spinnerConstante)
                    .addComponent(buttonAdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(textMultiplicacaoQuantidade))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerConstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSubtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMultiplicacaoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMultiplicacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Binarização");

        jLabel18.setText("Limiar:");

        buttonBinarizacao.setText("Binarizar");
        buttonBinarizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBinarizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerBinarizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(buttonBinarizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerBinarizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBinarizacao)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        buttonNegativo.setText("Negativo");
        buttonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegativoActionPerformed(evt);
            }
        });

        jLabel20.setText("Aplicar o negativo em uma imagem");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNegativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Modificação de resolução");

        jButton1.setText("Aumentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Diminuir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerResolucao)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerResolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelOperacacaoLayout = new javax.swing.GroupLayout(panelOperacacao);
        panelOperacacao.setLayout(panelOperacacaoLayout);
        panelOperacacaoLayout.setHorizontalGroup(
            panelOperacacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacacaoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOperacacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacacaoLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelOperacacaoLayout.setVerticalGroup(
            panelOperacacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOperacacaoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Processamento geral", panelOperacacao);

        textConstanteTransformacao.setText("0");

        textBetaTransformacao.setText("0");

        jLabel22.setText("Constante");

        jLabel23.setText("Beta");

        jButton7.setText("Aplicar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransformacaoPotenciaLayout = new javax.swing.GroupLayout(panelTransformacaoPotencia);
        panelTransformacaoPotencia.setLayout(panelTransformacaoPotenciaLayout);
        panelTransformacaoPotenciaLayout.setHorizontalGroup(
            panelTransformacaoPotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransformacaoPotenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransformacaoPotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22)
                    .addComponent(textConstanteTransformacao)
                    .addComponent(jLabel23)
                    .addComponent(textBetaTransformacao)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        panelTransformacaoPotenciaLayout.setVerticalGroup(
            panelTransformacaoPotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransformacaoPotenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textConstanteTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBetaTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Transformação potência", panelTransformacaoPotencia);

        textOperacoes.setEditable(false);

        jMenu2.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menuBar.add(jMenu2);

        jMenu1.setText("Imagem PGM");

        jMenuItem2.setText("Abrir imagem");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salvar imagem");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menuBar.add(jMenu1);

        jMenu3.setText("Imagem PPM");

        jMenuItem4.setText("Abrir imagem");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Salvar imagem");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textOperacoes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void avisoConstanteNegativa() {
        JOptionPane.showMessageDialog(this,
                "A quantidade da constante precisa ser positiva",
                "Constante não suportado",
                JOptionPane.ERROR_MESSAGE);
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        OpenPGMFile file = new OpenPGMFile();
        file.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new SavePGMFile().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void buttonFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltroActionPerformed
        // TODO add your handling code here:
        if (((int) spinnerQuantidadeFiltro.getValue()) % 2 == 0) {
            JOptionPane.showMessageDialog(this,
                    "A quantidade do filtro precisa ser ímpar",
                    "Tamanho do filtro não suportado",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (radioMedia.isSelected()) {
                textOperacoes.setText(Controlador.getInstance().media((int) spinnerQuantidadeFiltro.getValue()));
            }
            if (radioMediana.isSelected()) {
                textOperacoes.setText(Controlador.getInstance().mediana((int) spinnerQuantidadeFiltro.getValue()));
            }
        }
    }//GEN-LAST:event_buttonFiltroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new OpenPPMFile().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new SavePPMFile().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        new SavePPMChannelsFile().setVisible(true);
        if (radioExtracaoSalvarImagem.isSelected()) {
            Controlador.getInstance().dialogExtracaoRGB();

        }
        if (radioExtracaoUtilizarEmMemoria.isSelected()) {
            Controlador.getInstance().extracaoRGB(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioExtracaoUtilizarEmMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExtracaoUtilizarEmMemoriaActionPerformed
        // TODO add your handling code here:
        radioExtracaoTodos.setEnabled(false);
    }//GEN-LAST:event_radioExtracaoUtilizarEmMemoriaActionPerformed

    private void radioExtracaoSalvarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExtracaoSalvarImagemActionPerformed
        // TODO add your handling code here:
        radioExtracaoTodos.setEnabled(true);
    }//GEN-LAST:event_radioExtracaoSalvarImagemActionPerformed

    private void buttonJuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJuntarActionPerformed
        // TODO add your handling code here:
        String r = null, g = null, b = null;
        if (RedRed.isSelected()) {
            r = "r";
        }
        if (RedGreen.isSelected()) {
            r = "g";
        }
        if (RedBlue.isSelected()) {
            r = "b";
        }
        if (GreenRed.isSelected()) {
            g = "r";
        }
        if (GreenGreen.isSelected()) {
            g = "g";
        }
        if (GreenBlue.isSelected()) {
            g = "b";
        }
        if (BlueRed.isSelected()) {
            b = "r";
        }
        if (BlueGreen.isSelected()) {
            b = "g";
        }
        if (BlueBlue.isSelected()) {
            b = "b";
        }
        textOperacoes.setText(Controlador.getInstance().juncaoRGB(r, g, b));
    }//GEN-LAST:event_buttonJuntarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().equalizacaoGlobal());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().laplaciano(radioTipo1.isSelected(), radioTipo2.isSelected(), radioTipo3.isSelected(), radioTipo4.isSelected(), checkBoxAplicar.isSelected()));

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().highBoost((int) spinnerHighBoostMedia.getValue(), Double.valueOf(textHighBoostConstante.getText())));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkBoxAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAplicarActionPerformed

    private void buttonRotacao90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotacao90ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().rotacao90());
    }//GEN-LAST:event_buttonRotacao90ActionPerformed

    private void buttonRotacao180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotacao180ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().rotacao180());
    }//GEN-LAST:event_buttonRotacao180ActionPerformed

    private void buttonRotacaoMenos90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRotacaoMenos90ActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().rotacaoMenos90());
    }//GEN-LAST:event_buttonRotacaoMenos90ActionPerformed

    private void buttonEspelhamentoHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspelhamentoHorizontalActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().espelhamentoHorizontal());
    }//GEN-LAST:event_buttonEspelhamentoHorizontalActionPerformed

    private void buttonEspelhamentoVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspelhamentoVerticalActionPerformed
        textOperacoes.setText(Controlador.getInstance().espelhamentoVertical());
    }//GEN-LAST:event_buttonEspelhamentoVerticalActionPerformed

    private void buttonAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicaoActionPerformed
        // TODO add your handling code here:
        if ((int) spinnerConstante.getValue() < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().adicao((int) spinnerConstante.getValue()));
        }
    }//GEN-LAST:event_buttonAdicaoActionPerformed

    private void buttonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubtracaoActionPerformed
        // TODO add your handling code here:
        if ((int) spinnerConstante.getValue() < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().subtracao((int) spinnerConstante.getValue()));
        }
    }//GEN-LAST:event_buttonSubtracaoActionPerformed

    private void buttonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplicacaoActionPerformed
        // TODO add your handling code here:
        if (Float.parseFloat(textMultiplicacaoQuantidade.getText()) < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().multiplicacao(Float.parseFloat(textMultiplicacaoQuantidade.getText())));
        }
    }//GEN-LAST:event_buttonMultiplicacaoActionPerformed

    private void buttonBinarizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBinarizacaoActionPerformed
        // TODO add your handling code here:
        if ((int) spinnerBinarizacao.getValue() < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().binarizacao((int) spinnerBinarizacao.getValue()));
        }
    }//GEN-LAST:event_buttonBinarizacaoActionPerformed

    private void buttonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegativoActionPerformed
        // TODO add your handling code here:
        textOperacoes.setText(Controlador.getInstance().negativo());
    }//GEN-LAST:event_buttonNegativoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if ((int) spinnerResolucao.getValue() < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().diminuiResolucao((int) spinnerResolucao.getValue()));
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ((int) spinnerResolucao.getValue() < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().aumentaResolucao((int) spinnerResolucao.getValue()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(textConstanteTransformacao.getText()) < 0) {
            avisoConstanteNegativa();
        } else if (Double.parseDouble(textBetaTransformacao.getText()) < 0) {
            avisoConstanteNegativa();
        } else {
            textOperacoes.setText(Controlador.getInstance().transformacaoPotencia(Integer.parseInt(textConstanteTransformacao.getText()), Double.parseDouble(textBetaTransformacao.getText())));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     *
     * @param informcao
     */
    public void atualiza(String informcao) {
        jTextArea1.setText(informcao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoBlue() {
        return radioExtracaoBlue;
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoGreen() {
        return radioExtracaoGreen;
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoRed() {
        return radioExtracaoRed;
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoSalvarImagem() {
        return radioExtracaoSalvarImagem;
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoTodos() {
        return radioExtracaoTodos;
    }

    /**
     *
     * @return
     */
    public JRadioButton getRadioExtracaoUtilizarEmMemoria() {
        return radioExtracaoUtilizarEmMemoria;
    }

    /**
     *
     * @return
     */
    public JTextField getTextOperacoes() {
        return textOperacoes;
    }

    /**
     *
     * @param textOperacoes
     */
    public void setTextOperacoes(JTextField textOperacoes) {
        this.textOperacoes = textOperacoes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BlueBlue;
    private javax.swing.JRadioButton BlueGreen;
    private javax.swing.JRadioButton BlueRed;
    private javax.swing.JRadioButton GreenBlue;
    private javax.swing.JRadioButton GreenGreen;
    private javax.swing.JRadioButton GreenRed;
    private javax.swing.JRadioButton RedBlue;
    private javax.swing.JRadioButton RedGreen;
    private javax.swing.JRadioButton RedRed;
    private javax.swing.JButton buttonAdicao;
    private javax.swing.JButton buttonBinarizacao;
    private javax.swing.JButton buttonEspelhamentoHorizontal;
    private javax.swing.JButton buttonEspelhamentoVertical;
    private javax.swing.JButton buttonFiltro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonJuntar;
    private javax.swing.JButton buttonMultiplicacao;
    private javax.swing.JButton buttonNegativo;
    private javax.swing.JButton buttonRotacao180;
    private javax.swing.JButton buttonRotacao90;
    private javax.swing.JButton buttonRotacaoMenos90;
    private javax.swing.JButton buttonSubtracao;
    private javax.swing.JCheckBox checkBoxAplicar;
    private javax.swing.ButtonGroup griupJuncaoB;
    private javax.swing.ButtonGroup groupExtracaoRGB;
    private javax.swing.ButtonGroup groupExtracaoSalvarOuMemoria;
    private javax.swing.ButtonGroup groupJuncaoG;
    private javax.swing.ButtonGroup groupJuncaoR;
    private javax.swing.ButtonGroup groupLaplaciano;
    private javax.swing.ButtonGroup groupMediaMediana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelEqualizacaoGeral;
    private javax.swing.JPanel panelFiltragemEspacial;
    private javax.swing.JPanel panelInformacoes;
    private javax.swing.JPanel panelJuncaoExtracao;
    private javax.swing.JPanel panelOperacacao;
    private javax.swing.JPanel panelRotacao;
    private javax.swing.JPanel panelTransformacaoPotencia;
    private javax.swing.JRadioButton radioExtracaoBlue;
    private javax.swing.JRadioButton radioExtracaoGreen;
    private javax.swing.JRadioButton radioExtracaoRed;
    private javax.swing.JRadioButton radioExtracaoSalvarImagem;
    private javax.swing.JRadioButton radioExtracaoTodos;
    private javax.swing.JRadioButton radioExtracaoUtilizarEmMemoria;
    private javax.swing.JRadioButton radioMedia;
    private javax.swing.JRadioButton radioMediana;
    private javax.swing.JRadioButton radioTipo1;
    private javax.swing.JRadioButton radioTipo2;
    private javax.swing.JRadioButton radioTipo3;
    private javax.swing.JRadioButton radioTipo4;
    private javax.swing.JSpinner spinnerBinarizacao;
    private javax.swing.JSpinner spinnerConstante;
    private javax.swing.JSpinner spinnerHighBoostMedia;
    private javax.swing.JSpinner spinnerQuantidadeFiltro;
    private javax.swing.JSpinner spinnerResolucao;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField textBetaTransformacao;
    private javax.swing.JTextField textConstanteTransformacao;
    private javax.swing.JTextField textHighBoostConstante;
    private javax.swing.JTextField textMultiplicacaoQuantidade;
    private javax.swing.JTextField textOperacoes;
    // End of variables declaration//GEN-END:variables
}
